# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build-java

on:
  push:
    branches: [ main-java ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: 设置jdk11
          uses: actions/setup-java@v1
          with:
              java-version: 11
        - name: 缓存Maven
          uses: actions/cache@v2
          with:
              path: ~/.m2
              key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              restore-keys: ${{ runner.os }}-m2
        - name: 配置密码
          env:
              PROPERTIES: ${{ secrets.PROPERTIES }}
          run:
            echo "$PROPERTIES"> java/src/main/resources/application-local-dev.properties
        - name: 开始构建

          run: mvn --batch-mode --update-snapshots verify -f java/pom.xml
